


-- DROP TABLE public.hotels;

CREATE TABLE public.hotels (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	category int4 NOT NULL,
	CONSTRAINT hotels_pk PRIMARY KEY (id)
);


-- DROP TABLE public.bookings;

CREATE TABLE public.bookings (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	id_hotel int4 NOT NULL,
	date_from date NOT NULL,
	date_to date NOT NULL,
	email varchar NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id),
	CONSTRAINT bookings_fk FOREIGN KEY (id_hotel) REFERENCES public.hotels(id)
);

-- DROP TABLE public.availabilities;

CREATE TABLE public.availabilities (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	"date" date NOT NULL,
	id_hotel int4 NOT NULL,
	rooms int4 NOT NULL,
	CONSTRAINT availabilities_pk PRIMARY KEY (id),
	CONSTRAINT availabilities_fk FOREIGN KEY (id_hotel) REFERENCES public.hotels(id)
);